name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - uses: actions/checkout@v2
    - name: Build and Push Docker image
      run: |
        docker build . --file Dockerfile --tag renehr9102/act-environment:$CI_SHA_SHORT
        docker tag renehr9102/act-environment:$CI_SHA_SHORT renehr9102/act-environment:latest
    - name: Push Docker image
      run: |
        docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password ${{secrets.DOCKERHUB_PASSWORD}}
        docker push renehr9102/act-environment:$CI_SHA_SHORT
        docker push renehr9102/act-environment:latest
